checkfunargs: use defaults, allow ellipses
astamm/nloptr pull request #102
Opened 2022-01-28 17:43 UTC by gkane26

Small edits to allow the use of ellipses in the objective function. I've used this a bit for personal use, but it hasn't undergone extensive testing.

2022-01-30 16:39 UTC, astamm requested changes
Thanks for this PR. Can you please look into my comments?

2022-01-30 16:39 UTC, astamm commented on R/nloptr.R
> +                    has_default = !(fnms[mx1[i]] == "")
You should be checking the value in the list here, not the name, i.e. `has_default = !(flist[[mx1[i] + 1]] == "")`.

2022-01-30 16:39 UTC, astamm commented on R/nloptr.R
> +                m2 = match(rnms, fnms)
Why do you run again this? It is already in `m1`, isn't it?

2022-01-30 16:39 UTC, astamm commented on R/nloptr.R
> +            m2 = match(rnms, fnms)
Why do you run again this? It is already in `m1`, isn't it?

2022-01-30 16:39 UTC, astamm commented on R/nloptr.R
> +                        stop(paste(rnms[mx2[i]], "' passed to (...) in 'nloptr' but this is not required in the ", funname, " function.\n", sep = ""))
Please remove parenthesis around ellipsis.

2022-12-22 20:48 UTC, astamm commented
Hi @gkane26. Thanks for the PR. I do not know whether you had a chance to see my comments and finalise the PR so that we could close the related issue. Let me know.

2024-06-24 22:35 UTC, bbolker commented
Would you like me to take another crack at this?

2024-06-25 01:36 UTC, aadler commented
I’m not in front of my computer, but if I recall correctly, some of the helper wrapper functions use the ellipse to pass parameters to the underlying `nloptr` call, so ensuring that there is no conflict there would also be warranted.

2024-06-25 05:36 UTC, astamm commented
If you have time, that would be great.

2024-06-25 08:07 UTC, astamm commented
It seems related to #37 as well.

2025-08-13 08:43 UTC, astamm commented
Addressed in #196.

2025-08-13 08:43 UTC, closed without merging